apiVersion: v1
kind: Pod
metadata:
    namespace: flask
    name: yafa
    labels:
        environment: dev
spec:
    containers:
        - name: yafa
          image: martinezgerman/yafa
          livenessProbe:
            httpGet:
                path: /healthcheck
                port: 4040
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 4040
              name: yafa-app
              protocol: TCP
        
