apiVersion: v1
kind: Service
metadata:
    namespace: flask
    name: yet-another-flask-app
spec:
    selector:
        environment: dev
    ports:
        - protocol: TCP
          port: 4040
          targetPort: 4040
